ignoreWorkspaceRootCheck: true
minimumReleaseAgeExclude:
  - verkit@0.1.2
  - fast-npm-meta@2.2.0
  - get-npm-meta@0.2.2
shellEmulator: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - tinyexec@1.2.2
packages:
  - '!**/test/**'
overrides:
  fast-npm-meta: ^2.2.0
  package-manager-detector: ^1.7.0

catalogs:
  dev:
    '@antfu/eslint-config': ^9.1.0
    bumpp: ^11.1.0
    eslint: ^10.7.0
    tsdown: ^0.22.12
    tsx: ^4.23.1
    typescript: ^6.0.3
    vitest: ^4.1.10
  inlined:
    '@antfu/utils': ^9.3.0
    '@posva/prompts': ^2.4.4
    ansis: ^4.3.1
    cli-progress: ^3.12.0
    deepmerge: ^4.3.1
    detect-indent: ^7.0.2
    empathic: ^2.0.1
    get-npm-meta: ^0.2.2
  prod:
    '@antfu/ni': ^30.2.0
    '@henrygd/queue': ^1.2.0
    cac: ^7.0.0
    obug: ^2.1.4
    ofetch: ^1.5.1
    package-manager-detector: ^1.7.0
    pathe: ^2.0.3
    pnpm-workspace-yaml: ^1.6.1
    restore-cursor: ^5.1.0
    tinyexec: ^1.2.4
    tinyglobby: ^0.2.17
    unconfig: ^7.5.0
    verkit: ^0.1.2
    yaml: ^2.9.0
  types:
    '@types/cli-progress': ^3.11.6
    '@types/node': ^25.9.5
allowBuilds:
  esbuild: true
