ignoreWorkspaceRootCheck: true
minimumReleaseAgeExclude:
  - verkit@0.1.2
shellEmulator: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - tinyexec@1.2.2

packages:
  - '!**/test/**'
catalogs:
  dev:
    '@antfu/eslint-config': ^9.0.0
    bumpp: ^11.1.0
    eslint: ^10.4.0
    tsdown: ^0.22.0
    tsx: ^4.22.3
    typescript: ^6.0.3
    vitest: ^4.1.7
  inlined:
    '@antfu/utils': ^9.3.0
    '@posva/prompts': ^2.4.4
    ansis: ^4.3.0
    cli-progress: ^3.12.0
    deepmerge: ^4.3.1
    detect-indent: ^7.0.2
    empathic: ^2.0.1
    get-npm-meta: ^0.1.2
  prod:
    '@antfu/ni': ^30.1.0
    '@henrygd/queue': ^1.2.0
    cac: ^7.0.0
    obug: ^2.1.4
    ofetch: ^1.5.1
    package-manager-detector: ^1.6.0
    pathe: ^2.0.3
    pnpm-workspace-yaml: ^1.6.1
    restore-cursor: ^5.1.0
    tinyexec: ^1.2.2
    tinyglobby: ^0.2.16
    unconfig: ^7.5.0
    verkit: ^0.1.2
    yaml: ^2.9.0
  types:
    '@types/cli-progress': ^3.11.6
    '@types/node': ^25.9.1
allowBuilds:
  esbuild: true
