ignoreWorkspaceRootCheck: true
shellEmulator: true

trustPolicy: no-downgrade

packages:
  - '!**/test/**'
catalogs:
  dev:
    '@antfu/eslint-config': ^8.0.0
    bumpp: ^11.0.1
    eslint: ^10.1.0
    tsdown: ^0.21.7
    tsx: ^4.21.0
    typescript: ^6.0.2
    vitest: ^4.1.2
  inlined:
    '@antfu/utils': ^9.3.0
    '@posva/prompts': ^2.4.4
    ansis: ^4.2.0
    cli-progress: ^3.12.0
    debug: ^4.4.3
    deepmerge: ^4.3.1
    detect-indent: ^7.0.2
    get-npm-meta: ^0.1.1
    semver-es: ^0.1.0
  prod:
    '@antfu/ni': ^30.0.0
    '@henrygd/queue': ^1.2.0
    cac: ^7.0.0
    find-up-simple: ^1.0.1
    ofetch: ^1.5.1
    package-manager-detector: ^1.6.0
    pathe: ^2.0.3
    pnpm-workspace-yaml: ^1.6.0
    restore-cursor: ^5.1.0
    tinyexec: ^1.0.4
    tinyglobby: ^0.2.15
    unconfig: ^7.5.0
    yaml: ^2.8.3
  types:
    '@types/cli-progress': ^3.11.6
    '@types/debug': ^4.1.13
    '@types/node': ^25.5.0
onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
